env:
  browser: true
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parser: babel-eslint
parserOptions:
  ecmaVersion: 2019
  sourceType: module
rules:
  'no-unused-vars': ["error", { "argsIgnorePattern": "^_" }]
  'react/display-name': 0
  'react/prop-types': 0
  'react/react-in-jsx-scope': 0
  'semi': ["warn", "never"]
